// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/example/profile.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_grpc_example_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_example_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_grpc_example_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProfileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedUnixTime int64                  `protobuf:"varint,3,opt,name=created_unix_time,json=createdAt,proto3" json:"created_unix_time,omitempty"`
	UploadUrl       string                 `protobuf:"bytes,4,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_grpc_example_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_example_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_grpc_example_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProfileResponse) GetCreatedUnixTime() int64 {
	if x != nil {
		return x.CreatedUnixTime
	}
	return 0
}

func (x *GetProfileResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

var File_grpc_example_profile_proto protoreflect.FileDescriptor

const file_grpc_example_profile_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/example/profile.proto\x12\x16e2e.example.profile.v1\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"}\n" +
	"\x12GetProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x11created_unix_time\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x04 \x01(\tR\tuploadUrl2u\n" +
	"\x0eProfileService\x12c\n" +
	"\n" +
	"GetProfile\x12).e2e.example.profile.v1.GetProfileRequest\x1a*.e2e.example.profile.v1.GetProfileResponseB3Z1github.com/satorunooshie/e2e/grpc/v2/example;mainb\x06proto3"

var (
	file_grpc_example_profile_proto_rawDescOnce sync.Once
	file_grpc_example_profile_proto_rawDescData []byte
)

func file_grpc_example_profile_proto_rawDescGZIP() []byte {
	file_grpc_example_profile_proto_rawDescOnce.Do(func() {
		file_grpc_example_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_example_profile_proto_rawDesc), len(file_grpc_example_profile_proto_rawDesc)))
	})
	return file_grpc_example_profile_proto_rawDescData
}

var file_grpc_example_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_example_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: e2e.example.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil), // 1: e2e.example.profile.v1.GetProfileResponse
}
var file_grpc_example_profile_proto_depIdxs = []int32{
	0, // 0: e2e.example.profile.v1.ProfileService.GetProfile:input_type -> e2e.example.profile.v1.GetProfileRequest
	1, // 1: e2e.example.profile.v1.ProfileService.GetProfile:output_type -> e2e.example.profile.v1.GetProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_example_profile_proto_init() }
func file_grpc_example_profile_proto_init() {
	if File_grpc_example_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_example_profile_proto_rawDesc), len(file_grpc_example_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_example_profile_proto_goTypes,
		DependencyIndexes: file_grpc_example_profile_proto_depIdxs,
		MessageInfos:      file_grpc_example_profile_proto_msgTypes,
	}.Build()
	File_grpc_example_profile_proto = out.File
	file_grpc_example_profile_proto_goTypes = nil
	file_grpc_example_profile_proto_depIdxs = nil
}
